const translations = {
  en: {
      // All
      portfolioTitle: "Jackie Harmon's Portfolio",
      english: "English",
      spanish: "Spanish",
      portuguese: "Portuguese",
      welcomeLink: "Welcome",
      portfolioLink: "Portfolio",
      contactLink: "Contact Me",
      resumeLink: "Resume",
      footer: "Copyright &copy; 2024 Jackie Harmon. All rights reserved.",
      // Welcome
      introTitle: "Welcome to my portfolio!",
      introText: "I am a versatile professional with a passion for leveraging technology to enhance efficiency in various industries. My portfolio showcases not only my teaching prowess but also my expertise as a data visualization consultant, biomedical research analyst, and biomedical technician. Additionally, you'll find some of my fun personal projects on my website, offering a glimpse into my creativity and innovation beyond the professional realm. Dive in to explore how my multifaceted skillset can make a difference in your projects and endeavors.",
      authorization: "I am authorized to work professionally in both the USA and Brazil.",
      github: "Check out my GitHub:",
      // Contact
      nameTitle: "Jackie Harmon",
      detailsTitle: "Details",
      detailsText1: "With a Master's degree in Informatics, coupled with Bachelor's degrees in Engineering and Spanish, my academic background reflects a diverse intersection of disciplines. My professional journey includes roles as a professor, data visualization consultant and a biomedical engineering technician. Moreover, my experience working in multiple continents and proficiency in multiple languages allow me to collaborate effectively across borders and cultures.",
      detailsText2: "Please reach out to me so we can discuss how our skills and experiences can help each other achieve our goals.",
      contactInfoTitle: "Contact Info",
      email: "Email: jacquelynn.harmon@gmail.com",
      phone: "Phone: +1(470)836-5409",
      // Resume
      references: "References are available upon request. Unofficial transcripts, as well as certificates, are hyperlinked. If you want my resume, it is available in PDF format.",
      summaryQualifications: "SUMMARY OF QUALIFICATIONS",
      qualifications: "Background in programming and engineering. Skilled in code development and review, including creating documentation for software and IT processes. Proficient in translating complex technical information into clear, user-friendly manuals and guides. Excellent organizational and planning abilities, committed to delivering projects on time and within scope. Proven track record of collaborating with project managers, analysts, and subject matter experts to produce high-quality materials that meets regulatory requirements.",
      languagesTitle: "LANGUAGES",
      languages: "English (native) | Spanish (fluent) | Portuguese (fluent) | Mandarin (beginner)",
      technicalSkillsTitle: "TECHNICAL SKILLS",
      technicalSkills: "Technical Writing | HTML | Markdown | Microsoft Office Suite | Project Management | Python | C++ | CSS | JavaScript | Posit Cloud / R | Tableau | MATLAB | LabVIEW | SPSS | MiniTab | MySQL | SQLite3 | AutoDesk Inventor",
      militaryServiceTitle: "MILITARY SERVICE",
      militaryService: "US Army 2012-2016",
      workExperienceTitle: "WORK EXPERIENCE",
      westcliffUniversity: "Westcliff University",
      westcliffDates: "2/2023 - present",
      westcliffPosition: "ADJUNCT PROFESSOR (COLLEGE OF TECHNOLOGY & ENGINEERING)",
      westcliffTask1: "Graduate courses: Introduction to Data Analytics, Cloud Data Visualization, and Data in Artificial Intelligence & Machine Learning.",
      westcliffTask2: "Undergraduate course in the College of Business: Foundations of Statistics",
      middleGAStateUniversity: "Middle GA State University",
      middleGADates: "5/2023 – 5/2024",
      middleGAPosition: "LECTURER & ADJUNCT PROFESSOR (SCHOOL OF COMPUTING)",
      middleGATask1: "Undergraduate courses: Introduction to Computer Programming, Application Development, Web Development, Human-Computer Interaction, and FinTech.",
      claytonCountySchoolDistrict: "Clayton County School District",
      claytonCountyDates: "10/2022 - 8/2023",
      claytonCountyPosition: "SOFTWARE DEVELOPMENT TEACHER",
      claytonCountyTask1: "Created state curriculum documents and faculty training materials for the GADOE 9-12 IST (Intro to Software Technology) course, covering Cloud Computing, Computer Science, Game Design, Internet of Things, Programming, Web and Digital Design, and Web Development pathways.",
      iFood: "iFood",
      iFoodDates: "8/2019 - 2/2022",
      iFoodPosition: "DATA VISUALIZATION CONSULTANT (BRASILIA, BRAZIL)",
      iFoodTask1: "Collaborated with the cybersecurity team to document the implementation of a temporary Purple Team.",
      iFoodTask2: "Presented detailed technical reports and developed documentation solutions for international partners, facilitating clear communication of complex data insights.",
      iFoodTask3: "Created and maintained documentation for data visualization tools and processes.",
      nuBank: "NuBank",
      nuBankDates: "8/2019 - 2/2022",
      nuBankPosition: "DATA VISUALIZATION CONSULTANT (BRASILIA, BRAZIL)",
      nuBankTask1: "Worked closely with market risk analysts to document data analysis processes and create detailed risk dashboards, ensuring accuracy and clarity in the presentation of risk data.",
      nuBankTask2: "Developed standardized documentation and training guides to support the use of data visualization tools and techniques within the team.",
      navicentHealth: "Navicent Health Medical Center",
      navicentHealthDates: "10/2016 - 11/2018",
      navicentHealthPosition1: "ROBOTIC SURGERY RESEARCH ANALYST",
      navicentHealthTask1: "Provided prescriptive analytics and developed detailed reports with data collected from reconstructive surgery projects, documenting methodologies and findings until project completion.",
      navicentHealthPosition2: "BIOMEDICAL ENGINEERING TECHNICIAN II",
      navicentHealthTask2: "Debugged hospital equipment for ICU, PICU, and NNICU, maintaining detailed service logs and technical documentation.",
      navicentHealthTask3: "Mentored two interns, developing training materials that facilitated their successful transition into permanent positions.",
      internshipsTitle: "INTERNSHIPS",
      internship1: "Navicent Health Medical Center | Fall 2016 | BIOMEDICAL ENGINEERING TECHNICIAN INTERN",
      internship2: "Vein Specialists of the South | Summer 2014 | BIOFLUIDS / BIOMECHANICS RESEARCH ANALYST INTERN",
      internship3: "Mercer University | Spring 2014 | NANOPARTICLES RESEARCH ANALYST INTERN",
      projectsTitle: "PROJECTS",
      project1: "Development of a Mobile Ankle Joint Attachment for the Universal Prosthesis | 2016",
      project2: "Comparing the Mechanical Properties of Cancellous Bone between Pig Femur Bone, Deer Femur Bone, and Human Humerus Bone | 2016",
      project3: "The Study of Injury Biomechanics in the Wrist/Hand and Ankle/Foot for Tumbling Using the MatScan | 2015",
      educationTitle: "EDUCATION",
      education1: "MSIT Health Informatics | Middle Georgia State University | 2018 | 4.0",
      education2: "BSE Biomedical Engineering | Mercer University | 2016 | 3.4",
      education3: "BA Spanish | Mercer University | 2016 | 3.4",
      coursesCertificationsTitle: "COURSES AND CERTIFICATIONS",
      certification1: "Professional Certification in Data Science | Entity Academy & Woz U | 2023",
      certification2: "Engineering Technology Education I & II | GACE | 2022 | Passed-professional",
      certification3: "Leadership Development and Assessment Course | United States Army | 2016 | Top 15%",
      awardsHonorSocietiesTitle: "AWARDS AND HONOR SOCIETIES",
      award1: "Distinguished Military Graduate",
      award2: "Tau Beta Pi (Engineering Honor Society)",
      award3: "Phi Sigma Iota (Foreign Language Honor Society)",
      award4: "Alpha Phi Omega (National Service Fraternity)",
      award5: "HS Valedictorian",
      award6: "HS STAR Student (SAT)",
      volunteeringTitle: "VOLUNTEERING OPPORTUNITIES",
      volunteering1: "Fulbright Scholar Program (Summer 2023)",
      volunteering2: "Head Softball Coach (Spring 2022)",
      volunteering3: "Missionary (Fall 2019)",
      volunteering4: "Honduras Outreach, Inc (Summer 2015)",
      guestSpeakingTitle: "GUEST SPEAKING OPPORTUNITIES",
      speaking1: "Rotary Club of Griffin, GA (3/2023, 2/2018, 8/2013, 4/2012)",
      speaking2: "Kiwanis Club of Griffin, GA (4/2018)",
      speaking3: "GA Board of Education Annual Teacher Luncheon and Workshop (4/2014)",
      speaking4: "National Bank Outstanding Student Banquet (3/2013)"
  },
  es: {
      // Todo
      portfolioTitle: "Portafolio de Jackie Harmon",
      english: "Inglés",
      spanish: "Español",
      portuguese: "Portugués",
      welcomeLink: "Bienvenido",
      portfolioLink: "Portafolio",
      contactLink: "Contáctame",
      resumeLink: "Currículum",
            footer: "Derechos de autor &copy; 2024 Jackie Harmon. Todos los derechos reservados.",
      // Bienvenido
      introTitle: "¡Bienvenido a mi portafolio!",
      introText: "Soy un profesional versátil con una pasión por aprovechar la tecnología para mejorar la eficiencia en diversas industrias. Mi portafolio muestra no solo mi destreza en la enseñanza, sino también mi experiencia como consultor de visualización de datos, analista de investigación biomédica y técnico biomédico. Además, encontrarás algunos de mis proyectos personales divertidos en mi sitio web, que ofrecen una visión de mi creatividad e innovación más allá del ámbito profesional. Sumérgete para explorar cómo mi conjunto de habilidades multifacéticas puede marcar la diferencia en tus proyectos y esfuerzos.",
      authorization: "Estoy autorizado para trabajar profesionalmente en los EE. UU. y Brasil.",
      github: "Mira mi GitHub:",
      // Contáctame
      nameTitle: "Jackie Harmon",
      detailsTitle: "Detalles",
      detailsText1: "Con una maestría en informática, junto con licenciaturas en ingeniería y español, mi formación académica refleja una intersección diversa de disciplinas. Mi trayectoria profesional incluye roles como profesor, consultor de visualización de datos y técnico en ingeniería biomédica. Además, mi experiencia trabajando en múltiples continentes y mi dominio de varios idiomas me permiten colaborar eficazmente a través de fronteras y culturas.",
      detailsText2: "Póngase en contacto conmigo para que podamos discutir cómo nuestras habilidades y experiencias pueden ayudarnos a alcanzar nuestros objetivos.",
      contactInfoTitle: "Información de Contacto",
      email: "Correo Electrónico: jacquelynn.harmon@gmail.com",
      phone: "Teléfono: +1(470)836-5409",
      // Currículum
      references: "Las referencias están disponibles a pedido. Las transcripciones no oficiales, así como los certificados, están vinculados. Si desea mi currículum, está disponible en formato PDF.",
      summaryQualifications: "RESUMEN DE CALIFICACIONES",
      qualifications: "Experiencia en programación e ingeniería. Hábil en el desarrollo y revisión de código, incluyendo la creación de documentación para software y procesos de TI. Proficiente en traducir información técnica compleja en manuales y guías fáciles de usar. Excelentes habilidades organizativas y de planificación, comprometido a entregar proyectos a tiempo y dentro del alcance. Historial comprobado de colaboración con gerentes de proyecto, analistas y expertos en la materia para producir materiales de alta calidad que cumplen con los requisitos regulatorios.",
      languagesTitle: "IDIOMAS",
      languages: "Inglés (nativo) | Español (fluido) | Portugués (fluido) | Mandarín (principiante)",
      technicalSkillsTitle: "HABILIDADES TÉCNICAS",
      technicalSkills: "Redacción técnica | HTML | Markdown | Microsoft Office Suite | Gestión de proyectos | Python | C++ | CSS | JavaScript | Posit Cloud / R | Tableau | MATLAB | LabVIEW | SPSS | MiniTab | MySQL | SQLite3 | AutoDesk Inventor",
      militaryServiceTitle: "SERVICIO MILITAR",
      militaryService: "Ejército de los EE. UU. 2012-2016",
      workExperienceTitle: "EXPERIENCIA LABORAL",
      westcliffUniversity: "Westcliff University",
      westcliffDates: "2/2023 - presente",
      westcliffPosition: "PROFESOR ADJUNTO (FACULTAD DE TECNOLOGÍA E INGENIERÍA)",
      westcliffTask1: "Cursos de posgrado: Introducción a la Analítica de Datos, Visualización de Datos en la Nube y Datos en Inteligencia Artificial y Aprendizaje Automático.",
      westcliffTask2: "Curso de pregrado en la Facultad de Negocios: Fundamentos de Estadística",
      middleGAStateUniversity: "Middle GA State University",
      middleGADates: "5/2023 – 5/2024",
      middleGAPosition: "PROFESOR TITULAR Y ADJUNTO (ESCUELA DE COMPUTACIÓN)",
      middleGATask1: "Cursos de pregrado: Introducción a la Programación Informática, Desarrollo de Aplicaciones, Desarrollo Web, Interacción Humano-Computadora y FinTech.",
      claytonCountySchoolDistrict: "Clayton County School District",
      claytonCountyDates: "10/2022 - 8/2023",
      claytonCountyPosition: "PROFESOR DE DESARROLLO DE SOFTWARE",
      claytonCountyTask1: "Creó documentos curriculares estatales y materiales de capacitación para el curso GADOE 9-12 IST (Introducción a la Tecnología de Software), que cubren la Computación en la Nube, Ciencia de la Computación, Diseño de Juegos, Internet de las Cosas, Programación, Diseño Web y Digital, y Vías de Desarrollo Web.",
      iFood: "iFood",
      iFoodDates: "8/2019 - 2/2022",
      iFoodPosition: "CONSULTOR DE VISUALIZACIÓN DE DATOS (BRASILIA, BRASIL)",
      iFoodTask1: "Colaboró con el equipo de ciberseguridad para documentar la implementación de un Equipo Púrpura temporal.",
      iFoodTask2: "Presentó informes técnicos detallados y desarrolló soluciones de documentación para socios internacionales, facilitando la comunicación clara de ideas complejas.",
      iFoodTask3: "Creó y mantuvo documentación para herramientas y procesos de visualización de datos.",
      nuBank: "NuBank",
      nuBankDates: "8/2019 - 2/2022",
      nuBankPosition: "CONSULTOR DE VISUALIZACIÓN DE DATOS (BRASILIA, BRASIL)",
      nuBankTask1: "Trabajó en estrecha colaboración con analistas de riesgos de mercado para documentar procesos de análisis de datos y crear paneles de riesgos detallados, asegurando precisión y claridad en la presentación de datos de riesgo.",
      nuBankTask2: "Desarrolló documentación estandarizada y guías de capacitación para apoyar el uso de herramientas y técnicas de visualización de datos dentro del equipo.",
      navicentHealth: "Navicent Health Medical Center",
      navicentHealthDates: "10/2016 - 11/2018",
      navicentHealthPosition1: "ANALISTA DE INVESTIGACIÓN DE CIRUGÍA ROBÓTICA",
      navicentHealthTask1: "Proporcionó análisis prescriptivos y desarrolló informes detallados con datos recopilados de proyectos de cirugía reconstructiva, documentando metodologías y hallazgos hasta la finalización del proyecto.",
      navicentHealthPosition2: "TÉCNICO BIOMÉDICO II",
      navicentHealthTask2: "Depuró equipos hospitalarios para UCI, UCIP y UNIC, manteniendo registros de servicio detallados y documentación técnica.",
      navicentHealthTask3: "Mentoró a dos pasantes, desarrollando materiales de capacitación que facilitaron su transición exitosa a puestos permanentes.",
      internshipsTitle: "PASANTÍAS",
      internship1: "Navicent Health Medical Center | Otoño 2016 | PASANTE DE TÉCNICO BIOMÉDICO",
      internship2: "Vein Specialists of the South | Verano 2014 | PASANTE DE ANÁLISIS DE BIOFLUIDOS / BIOMECÁNICA",
      internship3: "Mercer University | Primavera 2014 | PASANTE DE ANÁLISIS DE NANOPARTÍCULAS",
      projectsTitle: "PROYECTOS",
      project1: "Desarrollo de un Adaptador de Articulación de Tobillo Móvil para la Prótesis Universal | 2016",
      project2: "Comparación de las Propiedades Mecánicas del Hueso Esponjoso entre Hueso de Fémur de Cerdo, Hueso de Fémur de Ciervo y Hueso de Húmero Humano | 2016",
      project3: "El Estudio de la Biomecánica de Lesiones en la Muñeca/Mano y Tobillo/Pie para Acrobacias Usando el MatScan | 2015",
      educationTitle: "EDUCACIÓN",
      education1: "MSIT Informática de la Salud | Middle Georgia State University | 2018 | 4.0",
      education2: "BSE Ingeniería Biomédica | Mercer University | 2016 | 3.4",
      education3: "BA Español | Mercer University | 2016 | 3.4",
      coursesCertificationsTitle: "CURSOS Y CERTIFICACIONES",
      certification1: "Certificación Profesional en Ciencia de Datos | Entity Academy & Woz U | 2023",
      certification2: "Educación en Tecnología de Ingeniería I & II | GACE | 2022 | Aprobado-profesional",
      certification3: "Curso de Desarrollo y Evaluación de Liderazgo | Ejército de los EE. UU. | 2016 | Top 15%",
      awardsHonorSocietiesTitle: "PREMIOS Y SOCIEDADES DE HONOR",
      award1: "Graduado Militar Distinguido",
      award2: "Tau Beta Pi (Sociedad de Honor de Ingeniería)",
      award3: "Phi Sigma Iota (Sociedad de Honor de Lenguas Extranjeras)",
      award4: "Alpha Phi Omega (Fraternidad Nacional de Servicio)",
      award5: "Valedictorian de HS",
      award6: "Estudiante Estrella de HS (SAT)",
      volunteeringTitle: "OPORTUNIDADES DE VOLUNTARIADO",
      volunteering1: "Programa de Becarios Fulbright (Verano 2023)",
      volunteering2: "Entrenador Principal de Softbol (Primavera 2022)",
      volunteering3: "Misionero (Otoño 2019)",
      volunteering4: "Honduras Outreach, Inc (Verano 2015)",
      guestSpeakingTitle: "OPORTUNIDADES PARA HABLAR COMO INVITADO",
      speaking1: "Club Rotario de Griffin, GA (3/2023, 2/2018, 8/2013, 4/2012)",
      speaking2: "Club Kiwanis de Griffin, GA (4/2018)",
      speaking3: "Almuerzo y Taller Anual de Maestros de la Junta de Educación de GA (4/2014)",
      speaking4: "Banquete de Estudiantes Destacados del Banco Nacional (3/2013)"
  },
  pt: {
      // Todo
      portfolioTitle: "Portfólio de Jackie Harmon",
      english: "Inglês",
      spanish: "Espanhol",
      portuguese: "Português",
      welcomeLink: "Bem-vindo",
      portfolioLink: "Portfólio",
      contactLink: "Contate-me",
      resumeLink: "Currículo",
      footer: "Direitos autorais &copy; 2024 Jackie Harmon. Todos os direitos reservados.",
      // Bem-vindo
      introTitle: "Bem-vindo ao meu portfólio!",
      introText: "Sou um profissional versátil com uma paixão por alavancar a tecnologia para aumentar a eficiência em várias indústrias. Meu portfólio mostra não apenas minha destreza no ensino, mas também minha experiência como consultor de visualização de dados, analista de pesquisa biomédica e técnico biomédico. Além disso, você encontrará alguns dos meus projetos pessoais divertidos em meu site, oferecendo um vislumbre de minha criatividade e inovação além do campo profissional. Mergulhe para explorar como meu conjunto de habilidades multifacetadas pode fazer a diferença em seus projetos e empreendimentos.",
      authorization: "Estou autorizado a trabalhar profissionalmente tanto nos EUA quanto no Brasil.",
      github: "Confira meu GitHub:",
      // Contate-me
      nameTitle: "Jackie Harmon",
      detailsTitle: "Detalhes",
      detailsText1: "Com um mestrado em Informática, junto com bacharelados em Engenharia e Espanhol, minha formação acadêmica reflete uma interseção diversificada de disciplinas. Minha trajetória profissional inclui funções como professor, consultor de visualização de dados e técnico em engenharia biomédica. Além disso, minha experiência de trabalho em vários continentes e minha proficiência em vários idiomas me permitem colaborar efetivamente através de fronteiras e culturas.",
      detailsText2: "Entre em contato comigo para que possamos discutir como nossas habilidades e experiências podem nos ajudar a alcançar nossos objetivos.",
      contactInfoTitle: "Informações de Contato",
      email: "Email: jacquelynn.harmon@gmail.com",
      phone: "Telefone: +1(470)836-5409",
      // Currículo
      references: "Referências estão disponíveis mediante solicitação. Transcrições não oficiais, bem como certificados, estão hiperligados. Se você quiser meu currículo, ele está disponível em formato PDF.",
      summaryQualifications: "RESUMO DAS QUALIFICAÇÕES",
      qualifications: "Experiência em programação e engenharia. Hábil no desenvolvimento e revisão de código, incluindo a criação de documentação para software e processos de TI. Proficiência em traduzir informações técnicas complexas em manuais e guias fáceis de usar. Excelentes habilidades organizacionais e de planejamento, comprometido com a entrega de projetos no prazo e dentro do escopo. Histórico comprovado de colaboração com gerentes de projeto, analistas e especialistas no assunto para produzir materiais de alta qualidade que atendam aos requisitos regulamentares.",
      languagesTitle: "IDIOMAS",
      languages: "Inglês (nativo) | Espanhol (fluente) | Português (fluente) | Mandarim (iniciante)",
      technicalSkillsTitle: "HABILIDADES TÉCNICAS",
      technicalSkills: "Redação técnica | HTML | Markdown | Microsoft Office Suite | Gerenciamento de Projetos | Python | C++ | CSS | JavaScript | Posit Cloud / R | Tableau | MATLAB | LabVIEW | SPSS | MiniTab | MySQL | SQLite3 | AutoDesk Inventor",
      militaryServiceTitle: "SERVIÇO MILITAR",
      militaryService: "Exército dos EUA 2012-2016",
      workExperienceTitle: "EXPERIÊNCIA PROFISSIONAL",
      westcliffUniversity: "Westcliff University",
      westcliffDates: "2/2023 - presente",
      westcliffPosition: "PROFESSOR ADJUNTO (FACULDADE DE TECNOLOGIA E ENGENHARIA)",
      westcliffTask1: "Cursos de pós-graduação: Introdução à Análise de Dados, Visualização de Dados na Nuvem e Dados em Inteligência Artificial e Aprendizado de Máquina.",
      westcliffTask2: "Curso de graduação na Faculdade de Negócios: Fundamentos de Estatística",
      middleGAStateUniversity: "Middle GA State University",
      middleGADates: "5/2023 – 5/2024",
      middleGAPosition: "PROFESSOR TITULAR E ADJUNTO (ESCOLA DE COMPUTAÇÃO)",
      middleGATask1: "Cursos de graduação: Introdução à Programação de Computadores, Desenvolvimento de Aplicações, Desenvolvimento Web, Interação Humano-Computador e FinTech.",
      claytonCountySchoolDistrict: "Clayton County School District",
      claytonCountyDates: "10/2022 - 8/2023",
      claytonCountyPosition: "PROFESSOR DE DESENVOLVIMENTO DE SOFTWARE",
      claytonCountyTask1: "Criou documentos curriculares estaduais e materiais de treinamento para o curso GADOE 9-12 IST (Introdução à Tecnologia de Software), cobrindo Computação em Nuvem, Ciência da Computação, Design de Jogos, Internet das Coisas, Programação, Design Digital e Web, e Caminhos de Desenvolvimento Web.",
      iFood: "iFood",
      iFoodDates: "8/2019 - 2/2022",
      iFoodPosition: "CONSULTOR DE VISUALIZAÇÃO DE DADOS (BRASÍLIA, BRASIL)",
      iFoodTask1: "Colaborou com a equipe de cibersegurança para documentar a implementação de uma Equipe Púrpura temporária.",
      iFoodTask2: "Apresentou relatórios técnicos detalhados e desenvolveu soluções de documentação para parceiros internacionais, facilitando a comunicação clara de ideias complexas.",
      iFoodTask3: "Criou e manteve documentação para ferramentas e processos de visualização de dados.",
      nuBank: "NuBank",
      nuBankDates: "8/2019 - 2/2022",
      nuBankPosition: "CONSULTOR DE VISUALIZAÇÃO DE DADOS (BRASÍLIA, BRASIL)",
      nuBankTask1: "Trabalhou em estreita colaboração com analistas de risco de mercado para documentar processos de análise de dados e criar painéis de risco detalhados, garantindo precisão e clareza na apresentação dos dados de risco.",
      nuBankTask2: "Desenvolveu documentação padronizada e guias de treinamento para apoiar o uso de ferramentas e técnicas de visualização de dados dentro da equipe.",
      navicentHealth: "Navicent Health Medical Center",
      navicentHealthDates: "10/2016 - 11/2018",
      navicentHealthPosition1: "ANALISTA DE PESQUISA EM CIRURGIA ROBÓTICA",
      navicentHealthTask1: "Forneceu análises prescritivas e desenvolveu relatórios detalhados com dados coletados de projetos de cirurgia reconstrutiva, documentando metodologias e descobertas até a conclusão do projeto.",
      navicentHealthPosition2: "TÉCNICO EM ENGENHARIA BIOMÉDICA II",
      navicentHealthTask2: "Depurou equipamentos hospitalares para UTI, UCIP e UCIN, mantendo registros detalhados de serviço e documentação técnica.",
      navicentHealthTask3: "Mentorou dois estagiários, desenvolvendo materiais de treinamento que facilitaram sua transição bem-sucedida para posições permanentes.",
      internshipsTitle: "ESTÁGIOS",
      internship1: "Navicent Health Medical Center | Outono 2016 | ESTAGIÁRIO DE TÉCNICO EM ENGENHARIA BIOMÉDICA",
      internship2: "Vein Specialists of the South | Verão 2014 | ESTAGIÁRIO DE ANÁLISE DE BIOFLUIDOS / BIOMECÂNICA",
      internship3: "Mercer University | Primavera 2014 | ESTAGIÁRIO DE ANÁLISE DE NANOPARTÍCULAS",
      projectsTitle: "PROJETOS",
      project1: "Desenvolvimento de um Anexo de Articulação de Tornozelo Móvel para a Prótese Universal | 2016",
      project2: "Comparação das Propriedades Mecânicas do Osso Esponjoso entre Osso do Fêmur de Porco, Osso do Fêmur de Veado e Osso do Úmero Humano | 2016",
      project3: "O Estudo da Biomecânica de Lesões no Punho/Mão e Tornozelo/Pé para Acrobacias Usando o MatScan | 2015",
      educationTitle: "EDUCAÇÃO",
      education1: "MSIT Informática em Saúde | Middle Georgia State University | 2018 | 4.0",
      education2: "BSE Engenharia Biomédica | Mercer University | 2016 | 3.4",
      education3: "BA Espanhol | Mercer University | 2016 | 3.4",
      coursesCertificationsTitle: "CURSOS E CERTIFICAÇÕES",
      certification1: "Certificação Profissional em Ciência de Dados | Entity Academy & Woz U | 2023",
      certification2: "Educação em Tecnologia de Engenharia I & II | GACE | 2022 | Aprovado-profissional",
      certification3: "Curso de Desenvolvimento e Avaliação de Liderança | Exército dos EUA | 2016 | Top 15%",
      awardsHonorSocietiesTitle: "PRÊMIOS E SOCIEDADES DE HONRA",
      award1: "Graduado Militar Distinto",
      award2: "Tau Beta Pi (Sociedade de Honra de Engenharia)",
      award3: "Phi Sigma Iota (Sociedade de Honra de Línguas Estrangeiras)",
      award4: "Alpha Phi Omega (Fraternidade Nacional de Serviço)",
      award5: "HS Valedictorian",
      award6: "HS STAR Student (SAT)",
      volunteeringTitle: "OPORTUNIDADES DE VOLUNTARIADO",
      volunteering1: "Programa de Bolsas Fulbright (Verão 2023)",
      volunteering2: "Treinador Principal de Softbol (Primavera 2022)",
      volunteering3: "Missionário (Outono 2019)",
      volunteering4: "Honduras Outreach, Inc (Verão 2015)",
      guestSpeakingTitle: "OPORTUNIDADES PARA FALAR COMO CONVIDADO",
      speaking1: "Rotary Club de Griffin, GA (3/2023, 2/2018, 8/2013, 4/2012)",
      speaking2: "Kiwanis Club de Griffin, GA (4/2018)",
      speaking3: "Almoço e Oficina Anual para Professores da Junta de Educação de GA (4/2014)",
      speaking4: "Banquete de Estudantes Destacados do Banco Nacional (3/2013)"
  }
};

// Function to change the language
function changeLanguage(lang) {
  const elements = document.querySelectorAll('[data-translate]');
  elements.forEach(el => {
      const translateKey = el.getAttribute('data-translate');
      if (translations[lang] && translations[lang][translateKey]) {
          el.innerText = translations[lang][translateKey];
      }
  });
  setActiveLanguageButton(lang); // Set the active button
}
